sudo: required
services:
  - docker

before_install:
  - docker build -t manomit/docker-react-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true manomit/docker-react-demo npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-demo"
  env: "DockerReactDemo-env"
  bucket_name: "elasticbeanstalk-us-east-1-072013170116"
  bucket_path: "docker-react-demo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY